[package]
name = "v8-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_v8 = "0.32.0"
tokio = { version = "1.12.0", features = ["full"] }

[lib]
name = "js"
path = "src/core/lib.rs"
